### ISSUE TITLE
[QUESTIONS] < this

### ISSUE THREAD

**Issue by TheAwesome98-Real** [CybertronicToon/ClassicalSharp-Survival#1]
- Can I have screenshots, before I try building this?
- How can I build this on i386 linux? (does gcc work, i've never built a c# program)
EDIT: I can build on x86_64.

**Comment by DT-is-not-available** [comment]
you need visual studio to build this, as it builds just like the old classicalsharp client

**Comment by TheAwesome98-Real** [comment]
Oh, okay.
